services:
  - type: web
    name: smartpos-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_r7DKAjGRLoe2@ep-solitary-mouse-afhhi6v8.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://smartpos-coral.vercel.app
      - key: SUPER_ADMIN_EMAIL
        value: superadmin@smartpos.com
      - key: SUPER_ADMIN_USERNAME
        value: SuperAdmin
      - key: SUPER_ADMIN_PASSWORD
        value: SuperAdmin@2025
